version: "3.8"

# compose for postgres, pgadmin, and nextjs
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currencies
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - 5050:80

  # nextjs:
  #   build: .
  #   restart: always
  #   environment:
  #     POSTGRES_PRISMA_URL: postgres://postgres:postgres@postgres:5432/postgres?schema=public
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres

volumes:
  postgres:
    driver: local
