name: pipeline moonpay

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  br-build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: feature branch build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Build Application
        run: pnpm build

      - name: Smoke test
        shell: bash
        run: |
          PORT=3001
          echo "App listen on $PORT"
          pnpm start &
          APP_PID=$!
          echo "Be pacient..."
          until curl -f http://localhost:$PORT/; do
            echo "waiting 1 second..."
            sleep 1
          done
         echo "Up and running :)"
         kill $APP_PID

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  pr-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: pull request build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: start postgres docker
        run: |
          docker run -d --rm \
            --name ci_postgres \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            -p 5432:5432 \
            postgres:17

      - name: Wait for Postgres
        run: |
          until docker exec ci_postgres pg_isready -U ${{ secrets.POSTGRES_USER }}; do
            echo "wait for postgres..."
            sleep 5
          done

      - name: Set Prisma URL
        run: |
          echo "POSTGRES_PRISMA_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@127.0.0.1:5432/${{ secrets.POSTGRES_DB }}?schema=public" >> $GITHUB_ENV

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run Prisma Migrations
        run: pnpm prisma migrate deploy

      - name: Build Application
        run: pnpm build

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
