name: Run PR checks

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: nnnabeel/devops-challenge

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Create docker image
        run: docker build -t ${{ env.DOCKER_REPO }}:latest -f Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.DOCKER_REPO }}:latest"
          format: 'table'
          output: 'trivy-report.txt'

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-report.txt
